# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capidx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mtest.A')),
            ],
        ),
    ]
